<?php
/**
 *  implements hook_theme
 * @return type
 */
function eme_wedding_theme() {
  return array(
    'wedding_left_navigation' => array(
      'variables' => array(
        'links' => array()
        ),
      'template' => 'templates/left-nav'
      )
    );

}
/**
 * Implements hook_block_info().
 */
function eme_wedding_block_info() {
  $blocks = array();
  $blocks['wedding_left_navigation'] = array(
    'info' => t('Wedding left navigation'),
    'cache' => DRUPAL_NO_CACHE,
    'weight' => 0,
    );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function eme_wedding_block_view($delta = '') {

  $block =  array();
  switch ($delta) {
    case 'wedding_left_navigation':
    $block['content'] = eme_wedding_get_let_nav();
    $block['weight'] = 0;
    break;
  }
  return $block;
}


function eme_wedding_get_let_nav(){

  if ($node = menu_get_object()) {
    $active = NULL;
    $wedding_main_node =  FALSE;
    if ($node->type=='weddings'){
      $wrapper = entity_metadata_wrapper('node', $node);
      $wedding_main_node =$wrapper->field_weddings_main->value();
    }
    if ($node->type=='weddings_main'){
      $wedding_main_node =$node;
      $active = 'active';
    }
    if (!$wedding_main_node){
      return;
    }

    $results = views_get_view_result('wedding', 'left_navigation',$wedding_main_node->nid);

    if (empty($results)){
      return NULL;
    }
    $links = array();
    $links[] = array('link'=>l($wedding_main_node->title,drupal_get_path_alias('node/'.$wedding_main_node->nid)),'active'=>$active);

    foreach($results as $row) {
      $links[] = array('link'=>l($row->node_title,drupal_get_path_alias('node/'.$row->nid)),'active'=>$active = ($row->nid==$node->nid)?'active':'');
    }

    return theme('wedding_left_navigation', array('links' => $links));
  }
}



function eme_wedding_form_node_form_alter(&$form, &$form_state, $form_id) {

 $query_parameters = drupal_get_query_parameters();
 if(!isset($query_parameters['hid'])){
  return ;
}

if ($form['#node']->type=='weddings_main'){

  if (isset($query_parameters['hid'])){
    $form['field_hotel']['und']['#value'] = $query_parameters['hid'];
    $form['field_hotel']['#prefix'] = '<div style="display:none;">';
    $form['field_hotel']['#suffix'] = '</div>';
  }
    // disable on edit form
  if (isset($form['#node']->nid)){
   $form['field_hotel']['#prefix'] = '<div style="display:none;">';
   $form['field_hotel']['#suffix'] = '</div>';
 }
}

if ($form['#node']->type=='weddings'){
  $query_parameters = drupal_get_query_parameters();

  $main_nid =  core_get_list_nid_from_hotel_nid($query_parameters['hid'],'weddings_main');

  if (isset($query_parameters['hid']) && $main_nid ){

    $form['field_weddings_main']['und']['#value'] = $main_nid;
    $form['field_weddings_main']['#prefix'] = '<div style="display:none;">';
    $form['field_weddings_main']['#suffix'] = '</div>';
  }
    //disable on edit form
  if (isset($form['#node']->nid)){
   $form['field_weddings_main']['#prefix'] = '<div style="display:none;">';
   $form['field_weddings_main']['#suffix'] = '</div>';
 }
}
}

/**
 * implements hook_core_content_types
 * @return [type] [description]
 */
function eme_wedding_core_content_types() {
  return array('weddings','weddings_main');
}
