<?php
/**
 * implements hook node insert
 * @param  [type] $node [description]
 * @return [type]       [description]
 */
// function eme_menu_node_insert($node) {

// }


/**
 * Implement hook_rules_action_info().
 */
function eme_menu_rules_action_info() {
  return array(
    'eme_menu_crate_new_hotel_menu' => array(
      'label' => t('Create New Hotel menu'),
      'group' => t('eMarketingEye'),
      'arguments' => array(
        'node' => array(
          'type' => 'node',
          'label' => t('Content')
          ),
        ),
      ),
    );
}



function eme_menu_crate_new_hotel_menu($node){

  if ($node->type !='hotel'){
    return;
  }

  $menu = array(
    'menu_name' => drupal_lookup_path('alias', "node/".$node->nid),
    'title' => $node->title,
    'description' => $node->title.' - manu.'
    );

  $exists = db_query("SELECT title FROM {menu_custom} WHERE menu_name=:menu_name", array(':menu_name' => $menu['menu_name']))->fetchField();
  if (!$exists) {
    menu_save($menu);
  }

  $link = array(
    'link_path' => drupal_lookup_path('alias', "node/".$node->nid),
    'link_title' => $node->title,
    'menu_name' => $menu['menu_name'],
    'weight' => 1,
    'expanded' => 0,
    );

  watchdog('eme_menu', print_r($link,TRUE));
  watchdog('eme_menu', "$$$$$$$$$$$$$$$$$$$");

  $exists = db_query("SELECT mlid from {menu_links} WHERE link_title=:link_title AND link_path=:link_path", array(':link_title' =>  $link['link_title'], ':link_path' => $link['link_path']))->fetchField();

  if (!$exists) {
    watchdog('eme_menu', "$$$$$$$$$$$$$$$$$$$");
    menu_link_save($link);
  }

}
